# -*- coding: utf-8 -*-
"""Telecom II.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ru9YNlHYE6WfKXu-9D5-ngLfEKjcmOD

#Librerias
"""

# Librerías utilizadas en el proyecto
import pandas as pd                      # Procesamiento de datos
import matplotlib.pyplot as plt           # Gráficos base
import seaborn as sns                    # Gráficos estadísticos
from imblearn.over_sampling import SMOTE # Balanceo de datos
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

"""#Extracción del Archivo Tratado"""

# Carga de datos
df.to_csv("datos_tratados.csv", index=False)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# --- CARGA DE DATOS ---

df.to_csv("datos_tratados.csv", index=False)

print("Datos cargados correctamente desde el archivo tratado.")

"""#Encoding"""

# Convertimos 'Churn' a numérico (0/1) en el DataFrame original
df_processed = df.copy()
df_processed['Churn'] = df_processed['Churn'].map({'Yes': 1, 'No': 0})

# Convertimos las variables categóricas restantes en variables numéricas (One-Hot Encoding)
# Ahora df_ml contendrá 'Churn' como 0/1 y las demás categóricas one-hot encoded
df_ml = pd.get_dummies(df_processed, drop_first=True)

# Calculamos la correlación con respecto al Churn
print("Correlaciones principales con el Churn:")
print(df_ml.corr()['Churn'].sort_values(ascending=False))

from sklearn.model_selection import train_test_split

# Definimos X (características) y (objetivo)
X = df_ml.drop('Churn', axis=1)
y = df_ml['Churn']

# Dividimos: 80% para entrenar, 20% para probar
# Usamos random_state para que los resultados sean reproducibles
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Entrenamiento: {X_train.shape[0]} muestras")
print(f"Prueba: {X_test.shape[0]} muestras")

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# 1. Instanciar modelos
log_model = LogisticRegression(max_iter=1000)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Eliminar filas con NaN en y_train (y correspondientemente en X_train)
# Esto asegura que no haya NaN en los datos de entrenamiento para los modelos
valid_train_indices = y_train.dropna().index
X_train = X_train.loc[valid_train_indices]
y_train = y_train.loc[valid_train_indices]

# 2. Entrenar
log_model.fit(X_train, y_train)
rf_model.fit(X_train, y_train)

print(" Modelos entrenados con éxito.")

from sklearn.metrics import classification_report

# Eliminar filas con NaN de X_test y y_test para asegurar una evaluación limpia
# Esto es importante si el NaN se originó en el preprocesamiento y no se eliminó antes del split
valid_test_indices = y_test.dropna().index
X_test_clean = X_test.loc[valid_test_indices]
y_test_clean = y_test.loc[valid_test_indices]

# Predicciones
y_pred_log = log_model.predict(X_test_clean)
y_pred_rf = rf_model.predict(X_test_clean)

print("=== REPORTE: REGRESIÓN LOGÍSTICA ===")
print(classification_report(y_test_clean, y_pred_log))

print("\n=== REPORTE: RANDOM FOREST ===")
print(classification_report(y_test_clean, y_pred_rf))

import matplotlib.pyplot as plt
import numpy as np

# Extraer coeficientes del modelo ganador (Logística)
importances = log_model.coef_[0]
features = X_train.columns

# Crear un DataFrame para visualizarlo mejor
feature_importance_df = pd.DataFrame({'Feature': features, 'Importance': importances})
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Mostrar los Top 5 impulsores de Churn y Top 5 de Retención
print(" Factores que más impulsan la CANCELACIÓN (Churn):")
print(feature_importance_df.head(5))

print("\nFactores que más ayudan a la RETENCIÓN:")
print(feature_importance_df.tail(5))

"""#Eliminación de Columnas Irrelevantes"""

# Lista de columnas que no aportan valor estadístico
cols_a_eliminar = ['customerID']

# Eliminación segura
df_final = df.drop(columns=cols_a_eliminar, errors='ignore')

print(f"Columnas eliminadas: {cols_a_eliminar}")
print(f"Total de columnas para el modelo: {len(df_final.columns)}")

"""#Verificación de la Proporción de Cancelación (Churn)"""

# Contar los valores de la columna Churn
counts = df_processed['Churn'].value_counts()
percentages = df_processed['Churn'].value_counts(normalize=True) * 100

print(" Proporción de Clientes (Churn):")
print(f"Permanecen (0): {counts[0]} clientes ({percentages[0]:.2f}%)")
print(f"Cancelaron (1): {counts[1]} clientes ({percentages[1]:.2f}%)")

"""#Balanceo de Clases"""

from imblearn.over_sampling import SMOTE
from collections import Counter

# 1. Instanciar SMOTE
smote = SMOTE(random_state=42)

# 2. Aplicar solo a los datos de ENTRENAMIENTO
# (Nunca al set de prueba, para mantener la evaluación realista)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

print(f"Antes de SMOTE: {Counter(y_train)}")
print(f"Después de SMOTE: {Counter(y_train_res)}")

"""#Normalización o Estandarización."""

from sklearn.preprocessing import StandardScaler

# 1. Identificamos las columnas numéricas con escalas grandes
cols_to_scale = ['tenure', 'Charges.Monthly', 'TotalCharges']

# 2. Instanciamos el escalador
scaler = StandardScaler()

# 3. Ajustamos y transformamos (usamos los datos balanceados con SMOTE)
# Creamos una copia para no perder los originales
X_train_final = X_train_res.copy()
X_test_final = X_test.copy()

X_train_final[cols_to_scale] = scaler.fit_transform(X_train_res[cols_to_scale])
X_test_final[cols_to_scale] = scaler.transform(X_test[cols_to_scale])

print(" Datos estandarizados. Ahora 'TotalCharges' y 'tenure' están en la misma escala.")

"""#Modelo"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Entrenar el modelo final (sin errores de convergencia)
final_model = LogisticRegression()
final_model.fit(X_train_final, y_train_res)

# The scaler object (`scaler`) and cleaned test data (`X_test_clean`, `y_test_clean`)
# exist from previous cells. We need to ensure X_test for prediction is aligned.

# Identify numerical columns to scale (from pJJ2gcrRBiFx)
cols_to_scale = ['tenure', 'Charges.Monthly', 'TotalCharges']

# Create an aligned and scaled version of X_test_clean for final prediction
X_test_final_aligned = X_test_clean.copy()
X_test_final_aligned[cols_to_scale] = scaler.transform(X_test_clean[cols_to_scale])

# 2. Predicciones using the aligned and scaled test set
y_pred_final = final_model.predict(X_test_final_aligned)

# 3. Mostrar resultados
print("=== REPORTE FINAL: TELECOM X (OPTIMIZADO) ===")
# Use y_test_clean for the classification report
print(classification_report(y_test_clean, y_pred_final))

# 4. Matriz de Confusión para el reporte visual
# Use y_test_clean for the confusion matrix
cm = confusion_matrix(y_test_clean, y_pred_final)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title('Matriz de Confusión Final')
plt.xlabel('Predicción')
plt.ylabel('Realidad')
plt.show()

"""#Correlación y Selección de Variables
##Análisis de Correlación
"""

import seaborn as sns
import matplotlib.pyplot as plt

# Calculamos la correlación de todas las variables con respecto a 'Churn'
plt.figure(figsize=(12, 8))
correlation_matrix = df_ml.corr()

# Filtramos solo la relación con Churn para que sea más fácil de leer
churn_corr = correlation_matrix['Churn'].sort_values(ascending=False)

# Graficamos
sns.heatmap(correlation_matrix[['Churn']].sort_values(by='Churn', ascending=False),
            annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlación de Variables con el Churn")
plt.show()

"""#Análisis Dirigido"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='Contract', hue='Churn', palette='viridis')
plt.title('Relación entre Tipo de Contrato y Cancelación')
plt.xlabel('Tipo de Contrato')
plt.ylabel('Cantidad de Clientes')
plt.show()

"""# Gasto Total × Cancelación (El Factor Valor)"""

plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='Churn', y='TotalCharges', palette='magma')
plt.title('Distribución de Gasto Total por Estado de Churn')
plt.xlabel('¿Canceló? (0=No, 1=Sí)')
plt.ylabel('Cargos Totales ($)')
plt.show()

"""#Gasto Mensual vs Gasto Total (Scatter Plot)"""

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='Charges.Monthly', y='TotalCharges', hue='Churn', alpha=0.5)
plt.title('Gasto Mensual vs Total: Patrones de Cancelación')
plt.show()

"""#Modelados predictivos
##Separación de Datos
"""

from sklearn.model_selection import train_test_split

# 1. Definimos X (características) y y  (objetivo)
X = df_ml.drop('Churn', axis=1)
y = df_ml['Churn']

# Eliminar filas con NaN de X y y antes de dividir, para asegurar que stratify funcione.
# Esto es crucial si el mapeo de Churn = 'Yes'/'No' a 1/0 introdujo NaNs, o si
# hay NaNs en otras columnas que afecten X.
valid_indices = y.dropna().index
X = X.loc[valid_indices]
y = y.loc[valid_indices]

# 2. División 80/20 (Un estándar sólido para tu volumen de ~7000 filas)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)

print(f"Entrenamiento: {X_train.shape[0]} registros")
print(f"Prueba: {X_test.shape[0]} registros")

"""#Creación de Modelos
##Modelo 1 Regresión Logística (Requiere Normalización)
 Este modelo funciona calculando una suma ponderada de las variables. Si una variable como TotalCharges tiene valores de 8,000 y SeniorCitizen tiene 1, el modelo creerá erróneamente que la primera es 8,000 veces más importante. La estandarización (que ya aplicamos) nivela el campo de juego para que el optimizador encuentre la solución sin sesgos de magnitud.
"""

from sklearn.linear_model import LogisticRegression

# Ya tenemos X_train_final (escalado y balanceado) y X_test_final_aligned (escalado)
log_model = LogisticRegression(max_iter=1000)
log_model.fit(X_train_final, y_train_res)

y_pred_log = log_model.predict(X_test_final_aligned)

"""#Modelo 2: Random Forest (No requiere Normalización)
Los bosques aleatorios funcionan mediante "preguntas" de sí/no (ej. ¿Es el gasto mensual mayor a $50?). Al árbol no le importa si el número es 50 o 5,000,000; la división lógica es la misma. Por eso, para este modelo usaremos los datos balanceados con SMOTE pero sin escalar, manteniendo su naturaleza original.
"""

from sklearn.ensemble import RandomForestClassifier

# Usamos X_train_res (balanceado pero NO escalado)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train_res, y_train_res)

# Para evaluar, usamos X_test_clean (sin escalar)
y_pred_rf = rf_model.predict(X_test_clean)

from sklearn.metrics import classification_report, accuracy_score

# --- EVALUANDO MODELO 1: REGRESIÓN LOGÍSTICA ---
print(" RESULTADOS: REGRESIÓN LOGÍSTICA")
print("Condición: Datos Normalizados + SMOTE")
print(classification_report(y_test_clean, y_pred_log))
print(f"Accuracy Total: {accuracy_score(y_test_clean, y_pred_log):.2f}")

print("\n" + "="*50 + "\n")

# --- EVALUANDO MODELO 2: RANDOM FOREST ---
print(" RESULTADOS: RANDOM FOREST")
print("Condición: Datos Originales (Sin Escalar) + SMOTE")
print(classification_report(y_test_clean, y_pred_rf))
print(f"Accuracy Total: {accuracy_score(y_test_clean, y_pred_rf):.2f}")

"""#Interpretación  y conclusiones
## Análisis de la Importancia de las Variables
"""

import pandas as pd
import matplotlib.pyplot as plt

# Extraer los coeficientes del modelo ganador
importances = pd.DataFrame({
    'Variable': X_train.columns,
    'Coeficiente': final_model.coef_[0]
}).sort_values(by='Coeficiente', ascending=False)

# Graficar
plt.figure(figsize=(10, 8))
sns.barplot(data=importances, x='Coeficiente', y='Variable', palette='coolwarm')
plt.title('Importancia de Variables: ¿Qué impulsa la cancelación?')
plt.show()

"""# Informe Final: Predicción y Retención de Churn
##Resumen del Rendimiento del Modelo

Tras evaluar múltiples arquitecturas, se seleccionó la Regresión Logística (entrenada con datos balanceados mediante SMOTE y estandarizados con StandardScaler).

Capacidad de Detección (Recall): 68%. El modelo identifica correctamente a casi 7 de cada 10 clientes que planean cancelar.

Precisión: 58%. Esto significa que más de la mitad de las acciones de retención estarán dirigidas a clientes que efectivamente están en riesgo real.

Exactitud Global (Accuracy): 79%. El modelo es robusto y confiable para la operación general.

                **Factores Críticos que Influyen en la Cancelación**

Basándonos en los coeficientes del modelo y el análisis exploratorio, estos son los tres pilares que definen la fuga de clientes:

Tipo de Contrato (El mayor predictor): Los clientes con contrato mes a mes tienen una probabilidad drásticamente superior de cancelar en comparación con aquellos en contratos de 1 o 2 años.

Tecnología de Internet: Existe una correlación positiva preocupante con la Fibra Óptica. A pesar de ser una tecnología superior, los clientes de este segmento presentan altas tasas de abandono, posiblemente por competitividad de precios o expectativas de servicio no cumplidas.

Barreras de Salida (Servicios de Valor): La ausencia de servicios como Seguridad Online y Soporte Técnico facilita la salida del cliente. Estos servicios actúan como "pegamento" en la relación comercial.

                   **Estrategias de Retención Propuestas**

Con base en los hallazgos, se sugieren las siguientes acciones inmediatas para Telecom X:

Programa de Migración de Contrato: Implementar una campaña dirigida a clientes "mes a mes" ofreciendo beneficios exclusivos (ej. meses gratis o upgrades de velocidad) si migran a un contrato anual.

Auditoría del Segmento Fibra: Realizar una investigación técnica y de mercado sobre el servicio de fibra óptica para entender si el problema es de estabilidad técnica o de percepción de valor frente a la competencia.

Venta Cruzada de "Servicios Ancla": Promover activamente los servicios de Online Security y Tech Support en los primeros 3 meses de vida del cliente. Los datos muestran que los clientes con estos servicios tienen una mayor "antigüedad" (tenure).

Alerta Temprana (Early Warning System): Utilizar el modelo para generar una lista semanal de clientes con una probabilidad de churn superior al 70% y enviarla al equipo de fidelización para un contacto proactivo.

                      **Conclusión General**

El proyecto demuestra que la cancelación no es aleatoria; es predecible. Al pasar de un enfoque reactivo a uno proactivo, Telecom X no solo puede ahorrar los altos costos de adquisición de nuevos clientes, sino también mejorar la salud de su base instalada mediante decisiones basadas en evidencia.
"""